recipe_scanner.settings:
  type: config_object
  label: 'Recipe Scanner settings'
  mapping:
    openai_model:
      type: string
      label: 'OpenAI Model'
    scan_prompt:
      type: string
      label: 'Scan Prompt'
