recipe_scanner.settings:
  type: config_object
  label: 'Recipe Scanner settings'
  mapping:
    openai_model:
      type: string
      label: 'OpenAI Model'
    scan_prompt:
      type: string
      label: 'Scan Prompt'

views.filter.ingredient_autocomplete:
  type: views.filter.many_to_one
  label: 'Ingredient autocomplete filter'
  mapping:
    error_message:
      type: boolean
      label: 'Display error message'
