<?php

/**
 * @file
 * Functions to support theming in the indie theme.
 */

/**
 * Implements hook_preprocess_HOOK() for html.html.twig.
 */
function indie_preprocess_html(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for page.html.twig.
 */
function indie_preprocess_page(&$variables) {

}

/**
 * Implements hook_preprocess_HOOK() for node.html.twig.
 */
function indie_preprocess_node(&$variables) {
  $node = $variables['node'];
  $variables['date'] = \Drupal::service('date.formatter')
    ->format($node->getCreatedTime(), 'custom', 'F j, Y');
  $variables['display_submitted'] = FALSE;
}
